language: node_js
node_js:
  - '6.9.1'
script:
  - echo "Deploying!"
install:
  - npm install -g firebase-tools
  - npm install -g @angular/cli@latest
  - npm install
after_success:
  - ng build --prod --aot
  - firebase deploy --token $FIREBASE_TOKEN